<html>
<?php include('components/head.phtml'); ?>
<body class="min-vh-100 d-flex flex-column">
<?php include('components/header.phtml'); ?>

<?php foreach ($messages as $key => $value): ?>
    <div class="alert alert-<?= $key ?>" role="alert">
    <?= $value[0] ?>
    </div>
<?php endforeach ?>

<main class="flex-grow-1">
    <div class="container-lg mt-3">
    <h1>Сайт: <?= $url->getUrlName() ?></h1>
        <div class="table-responsive">
            <table class="table table-bordered table-hover text-nowrap" data-test="url">
      <tbody>
        <tr>
          <td>ID</td>
          <td><?= $url->getId() ?></td>
        </tr>
        <tr>
          <td>Имя</td>
          <td><?= $url->getUrlName() ?></td>
        </tr>
        <tr>
          <td>Дата создания</td>
          <td><?= $url->getTimeCreated() ?></td>
        </tr>
      </tbody>
    </table>
  </div>
  <h2 class="mt-5 mb-3">Проверки</h2>
  <form method="post" action="/urls/<?= $url->getId() ?>/checks">
    <input type="submit" class="btn btn-primary" value="Запустить проверку">
  </form>
  <table class="table table-bordered table-hover" data-test="checks">
    <thead>
      <tr>
        <th>ID</th>
        <th>Код ответа</th>
        <th>h1</th>
        <th>title</th>
        <th>description</th>
        <th>Дата создания</th>
      </tr>
    </thead>
    <tbody>
    <?php foreach ($checks as $check): ?>
    <tr>
        <td><?= $check->getId() ?></td>
        <td><?= $check->getStatusCode() ?></td>
        <td><?= $check->getH1() ?></td>
        <td><?= $check->getTitle() ?></td>
        <td><?= $check->getDescription() ?></td>
        <td><?= $check->getTimeCreated() ?></td>
    </tr> 
    <?php endforeach ?>
    </tbody>

  </table>
        </div>
    </main>

<?php include('components/footer.phtml') ?>
