<html>
<?php include('components/head.phtml'); ?>
<body class="min-vh-100 d-flex flex-column">
<?php include('components/header.phtml'); ?>

<main class="flex-grow-1">
    <div class="container-lg mt-3">
        <h1>Сайт: https://php-page-analyzer-ru.hexlet.app</h1>
        <div class="table-responsive">
            <table class="table table-bordered table-hover text-nowrap" data-test="url">
      <tbody>
        <tr>
          <td>ID</td>
          <td>1</td>
        </tr>
        <tr>
          <td>Имя</td>
          <td>https://php-page-analyzer-ru.hexlet.app</td>
        </tr>
        <tr>
          <td>Дата создания</td>
          <td>2025-02-22 08:13:00</td>
        </tr>
      </tbody>
    </table>
  </div>
  <h2 class="mt-5 mb-3">Проверки</h2>
  <form method="post" action="/urls/1/checks">
    <input type="submit" class="btn btn-primary" value="Запустить проверку">
  </form>
  <table class="table table-bordered table-hover" data-test="checks">
    <thead>
      <tr>
        <th>ID</th>
        <th>Код ответа</th>
        <th>h1</th>
        <th>title</th>
        <th>description</th>
        <th>Дата создания</th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($checks as $check): ?>
          </tbody>
  </table>
        </div>
    </main>

<?php include('components/footer.phtml') ?>
